[wokwi]
version = 1

[[esp32]]
id = "esp32_tx"
firmware = "../src/esp-transmisor/build/esp-transmisor.bin"
flash_size = 4

[[esp32]]
id = "esp32_rx"
firmware = "../src/esp-receptor/build/esp-receptor.bin"
flash_size = 4